# Travis CI configuration file.

language: php

php:
    - "7.1"

install:
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - phpcs --version
    - phpunit --version
    - phpcs -p -s -v -n --standard=./phpcs.xml.dist
    - phpunit tests
