# Travis CI configuration file.

language: php

php:
    - "7.0"

install:
    - pyrus install http://phptal.org/latest.tar.gz
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - phpcs --version
    - phpunit --version
    - phpcs -p -s -v -n src --standard=./phpcs.xml.dist
