# Travis CI configuration file.

language: php

php:
    - "7.0"

install:
    - composer install
    - phpenv rehash

script:
    - vendor/bin/phpcs --version
    - phpunit --version
    - vendor/bin/phpcs -p -s -v -n --standard=./phpcs.xml.dist
    - phpunit --bootstrap="vendor/autoload.php" tests
